// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epepexbpizctmhuhkozi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwZXBleGJwaXpjdG1odWhrb3ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMzk3NjUsImV4cCI6MjA2NjkxNTc2NX0.nEgLrPTTCx7pDo7_QGmr15iDCuQ4twxbbLHdQGF0Fys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});